routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\WebsiteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('home', [HomeController::class, 'index'])->name('home');

Route::resource('websites', WebsiteController::class);
Route::delete('websites/force/{website}', [WebsiteController::class, 'forceDestroy'])->name('websites.force.destroy');
Route::put('websites/restore/{website}', [WebsiteController::class, 'restore'])->name('websites.restore');

Route::get('customer/{slug}/websites', [WebsiteController::class, 'index'])->name('websites.customer');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    public function websites()
    {
        return $this->hasMany(Website::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Website.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Website extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'logo',
        'madein',
        'url_dev',
        'url_dev_admin',
        'access_dev',
        'url_prod',
        'url_prod_admin',
        'access_prod',
        'customer_id'
    ];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/WebsiteController.php
<?php

namespace App\Http\Controllers;

use App\Models\{Website, Customer};
use Illuminate\Http\Request;
use App\Http\Requests\Website as WebsiteRequest;


class WebsiteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($slug = null)
    {
        // $websites = Website::withTrashed()->oldest('name')->paginate(20);
        // return view('index', compact('websites'));

        // On distingue le cas où on fournit un slug de catégorie et le cas où on n'en fournit pas
        $query = $slug ? Customer::whereSlug($slug)->firstOrFail()->websites() : Website::query();
        $websites = $query->withTrashed()->oldest('name')->paginate(50);
        $customers = Customer::all();
        return view('index', compact('websites', 'customers', 'slug'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //return view('create');
        $customers = Customer::all();
        return view('create', compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WebsiteRequest $websiteRequest)
    {
        Website::create($websiteRequest->all());
        return redirect()->route('websites.index')->with('info', 'Le site a bien été créé');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Website $website)
    {
        // return view('show', compact('website'));
        $customer = $website->customer->name;
        return view('show', compact('website', 'customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Website $website)
    {
        return view('edit', compact('website'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(WebsiteRequest $websiteRequest, Website $website)
    {
        $website->update($websiteRequest->all());
        return redirect()->route('websites.index')->with('info', 'Le site a bien été modifié');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy(Website $website)
    {
        $website->delete();
        return back()->with('info', 'Le site a bien été mis dans la corbeille.');
    }

    public function forceDestroy($id)
    {
        Website::withTrashed()->whereId($id)->firstOrFail()->forceDelete();
        return back()->with('info', 'Le site a bien été supprimé définitivement dans la base de données.');
    }

    public function restore($id)
    {
        Website::withTrashed()->whereId($id)->firstOrFail()->restore();
        return back()->with('info', 'Le site a bien été restauré.');
    }
}

resources/views/create.blade.php
@extends('layouts.master')
@section('content')
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Création d'un site</p>
        </header>
        <div class="card-content">
            <div class="content">
                <form action="{{ route('websites.store') }}" method="POST">
                    @csrf
                    <div class="field">
                        <label class="label">Client</label>
                        <div class="select">
                            <select name="customer_id">
                                @foreach ($customers as $customer)
                                    <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Nom du site</label>
                        <div class="control">
                            <input class="input @error('name') is-danger @enderror" type="text" name="name"
                                value="{{ old('name') }}" placeholder="Nom du site">
                        </div>
                        @error('name')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>

                    {{-- <div class="field">
                        <label class="label">Année de diffusion</label>
                        <div class="control">
                            <input class="input" type="number" name="year" value="{{ old('year') }}" min="1950"
                                max="{{ date('Y') }}">
                        </div>
                        @error('year')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div> --}}

                    <div class="field">
                        <label class="label">Made In Uniweb ?</label>
                        <div class="field">
                            <input type="radio" id="yes" name="madein" value="1">
                            <label for="yes">Oui</label>
                        </div>
                        <div>
                            <input type="radio" id="no" name="madein" value="0" checked>
                            <label for="no">Non</label>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">URL DEV</label>
                        <div class="control">
                            <input class="input @error('url_dev') is-danger @enderror" type="text" name="url_dev"
                                value="{{ old('url_dev') }}" placeholder="URL du site en dev">
                        </div>
                        @error('url_dev')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL DEV ADMIN</label>
                        <div class="control">
                            <input class="input @error('url_dev_admin') is-danger @enderror" type="text"
                                name="url_dev_admin" value="{{ old('url_dev_admin') }}"
                                placeholder="URL admin du site en dev">
                        </div>
                        @error('url_dev_admin')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">ACCES SITE EN DEV</label>
                        <div class="control">
                            <input class="input @error('access_dev') is-danger @enderror" type="text" name="access_dev"
                                value="{{ old('access_dev') }}" placeholder="Accès du site en dev">
                        </div>
                        @error('access_dev')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL PROD</label>
                        <div class="control">
                            <input class="input @error('url_prod') is-danger @enderror" type="text" name="url_prod"
                                value="{{ old('url_prod') }}" placeholder="URL du site en prod">
                        </div>
                        @error('url_prod')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL PROD ADMIN</label>
                        <div class="control">
                            <input class="input @error('url_prod_admin') is-danger @enderror" type="text"
                                name="url_prod_admin" value="{{ old('url_prod_admin') }}"
                                placeholder="URL admin du site en prod">
                        </div>
                        @error('url_prod_admin')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">ACCES SITE EN PROD</label>
                        <div class="control">
                            <input class="input @error('access_prod') is-danger @enderror" type="text" name="access_prod"
                                value="{{ old('access_prod') }}" placeholder="Accès du site en prod">
                        </div>
                        @error('access_prod')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-link">Créer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends('layouts.master')
@section('content')
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Modification d'un site</p>
        </header>
        <div class="card-content">
            <div class="content">
                <form action="{{ route('websites.update', $website->id) }}" method="POST">
                    @csrf
                    @method('put')
                    <div class="field">
                        <label class="label">Nom</label>
                        <div class="control">
                            <input class="input @error('name') is-danger @enderror" type="text" name="name"
                                value="{{ old('name', $website->name) }}" placeholder="Titre du website">
                        </div>
                        @error('name')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">Made In Uniweb ?</label>
                        <div class="field">
                            <input type="radio" id="yes" name="madein" value="1">
                            <label for="yes">Oui</label>
                        </div>
                        <div>
                            <input type="radio" id="no" name="madein" value="0" checked>
                            <label for="no">Non</label>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">URL DEV</label>
                        <div class="control">
                            <input class="input @error('url_dev') is-danger @enderror" type="text" name="url_dev"
                                value="{{ old('url_dev', $website->url_dev) }}" placeholder="URL du site en dev">
                        </div>
                        @error('url_dev')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL DEV ADMIN</label>
                        <div class="control">
                            <input class="input @error('url_dev_admin') is-danger @enderror" type="text"
                                name="url_dev_admin" value="{{ old('url_dev_admin', $website->url_dev_admin) }}"
                                placeholder="URL admin du site en dev">
                        </div>
                        @error('url_dev_admin')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">ACCES SITE EN DEV</label>
                        <div class="control">
                            <input class="input @error('access_dev') is-danger @enderror" type="text" name="access_dev"
                                value="{{ old('access_dev', $website->access_dev) }}" placeholder="Accès du site en dev">
                        </div>
                        @error('access_dev')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL PROD</label>
                        <div class="control">
                            <input class="input @error('url_prod') is-danger @enderror" type="text" name="url_prod"
                                value="{{ old('url_prod', $website->url_prod) }}" placeholder="URL du site en prod">
                        </div>
                        @error('url_prod')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">URL PROD ADMIN</label>
                        <div class="control">
                            <input class="input @error('url_prod_admin') is-danger @enderror" type="text"
                                name="url_prod_admin" value="{{ old('url_prod_admin', $website->url_prod_admin) }}"
                                placeholder="URL admin du site en prod">
                        </div>
                        @error('url_prod_admin')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <label class="label">ACCES SITE EN PROD</label>
                        <div class="control">
                            <input class="input @error('access_prod') is-danger @enderror" type="text" name="access_prod"
                                value="{{ old('access_prod', $website->access_prod) }}"
                                placeholder="Accès du site en prod">
                        </div>
                        @error('access_prod')
                            <p class="help is-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="field">
                        <div class="control">
                            <button class="button is-link">Modifier</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('css')
    <style>
        .card-footer {
            justify-content: center;
            align-items: center;
            padding: 0.4em;
        }

        select,
        .is-info {
            margin: 0.3em;
        }

    </style>
@endsection
@section('content')
    @if (session()->has('info'))
        <div class="notification is-success">
            {{ session('info') }}
        </div>
    @endif
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Websites</p>
            <div class="select">
                <select onchange="window.location.href = this.value">
                    <option value="{{ route('websites.index') }}" @unless($slug) selected @endunless>Trier par client
                    </option>
                    @foreach ($customers as $customer)
                        <option value="{{ route('websites.customer', $customer->slug) }}"
                            {{ $slug == $customer->slug ? 'selected' : '' }}>{{ $customer->name }}</option>
                    @endforeach
                </select>
            </div>
            <a class="button is-info" href="{{ route('websites.create') }}">Ajouter un site</a>
        </header>
        <div class="card-content">
            <div class="content">
                <table class="table is-hoverable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nom du site</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($websites as $website)
                            <tr @if ($website->deleted_at) class="has-background-grey-lighter" @endif>
                                <td>{{ $website->id }}</td>
                                <td><b>{{ $website->name }}</b></td>
                                <td>
                                    @if ($website->deleted_at)
                                        <form action="{{ route('websites.restore', $website->id) }}" method="post">
                                            @csrf
                                            @method('PUT')
                                            <button class="button is-primary" type="submit">Restaurer</button>
                                        </form>
                                    @else
                                        <a class="button is-primary"
                                            href="{{ route('websites.show', $website->id) }}">Voir</a>
                                    @endif
                                </td>
                                <td>
                                    @if ($website->deleted_at)
                                    @else
                                        <a class="button is-warning"
                                            href="{{ route('websites.edit', $website->id) }}">Modifier</a>
                                    @endif
                                </td>
                                <td>
                                    <form
                                        action="{{ route($website->deleted_at ? 'websites.force.destroy' : 'websites.destroy', $website->id) }}"
                                        method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="button is-danger" type="submit">Supprimer</button>
                                    </form>
                                </td>
                            </tr>

                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <footer class="card-footer is-centered">
            {{ $websites->links() }}
        </footer>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/show.blade.php
@extends('layouts.master')
@section('css')
    <style>
        .card-footer {
            justify-content: center;
            align-items: center;
            padding: 0.4em;
        }

        select,
        .is-info {
            margin: 0.3em;
        }

    </style>
@endsection
@section('content')
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Nom du site : {{ $website->name }}</p>
            <p class="card-header-title">Client : {{ $customer }}</p>
            <img src="{{ $website->logo }}" style="width: 100px; height:100px; object-fit:cover">
        </header>
        <div class="card-content">
            <div class="content">
                <p><b>Made In UNIWEB ? :</b> {{ $website->logo == 1 ? 'Oui' : 'Non' }}</p>
                <p><b>URL DEV :</b> {{ $website->url_dev }}</p>
                <p><b>URL DEV ADMIN :</b> {{ $website->url_dev_admin }}</p>
                <p><b>ACCESS DEV :</b> {{ $website->access_dev }}</p>
                <p><b>URL PROD :</b> {{ $website->url_prod }}</p>
                <p><b>URL PROD ADMIN :</b> {{ $website->url_prod_admin }}</p>
                <p><b>ACCESS PROD :</b> {{ $website->access_prod }}</p>
            </div>
        </div>
    </div>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
initial-scale=1">
    <title>Websites Uniweb</title>
    {{-- <link rel="stylesheet" href="{{ asset('css/app.css') }}"> --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    @yield('css')
</head>

<body>
    <main class="section">
        <div class="container">
            @yield('content')
        </div>
    </main>
    {{-- <script src="{{ asset('js/app.js') }}"></script> --}}

</body>

</html>